### ISSUE TITLE
CUDA 12.8 does not work with accel sim.

### ISSUE THREAD

**Issue by HakamAtassi** [accel-sim/accel-sim-framework#508]
I'm running the provided cuda 12.8 docker, attempting to build accel sim for use in my work. I have quite a few questions, as this build seems to be broken as far as I can tell. 

For one thing, though nvbit seems to build and run fine, attempting to build accel sim with:

```
pip3 install -r requirements.txt
source ./gpu-simulator/setup_environment.sh

# Build with make
make -j -C ./gpu-simulator/
```

I pass the sourcing versioning check, only to fail during the building process with:

```
cuda-sim.cc:135:14: error: invalid use of incomplete type 'const struct textureReference'
  135 |     assert(tr->normalized == texref->normalized &&
      |              ^~
In file included from cuda-sim.h:36:
../abstract_hardware_model.h:529:16: note: forward declaration of 'struct textureReference'
  529 |   const struct textureReference *m_texref;
      |                ^~~~~~~~~~~~~~~~
cuda-sim.cc:135:36: error: invalid use of incomplete type 'const struct textureReference'
  135 |     assert(tr->normalized == texref->normalized &&
      |                                    ^~
../abstract_hardware_model.h:529:16: note: forward declaration of 'struct textureReference'
  529 |   const struct textureReference *m_texref;
      |                ^~~~~~~~~~~~~~~~
cuda-sim.cc:136:14: error: invalid use of incomplete type 'const struct textureReference'
  136 |            tr->filterMode == texref->filterMode &&
      |              ^~
../abstract_hardware_model.h:529:16: note: forward declaration of 'struct textureReference'
  529 |   const struct textureReference *m_texref;
      |                ^~~~~~~~~~~~~~~~
cuda-sim.cc:136:36: error: invalid use of incomplete type 'const struct textureReference'
  136 |            tr->filterMode == texref->filterMode &&
      |                                    ^~
../abstract_hardware_model.h:529:16: note: forward declaration of 'struct textureReference'
  529 |   const struct textureReference *m_texref;
      |                ^~~~~~~~~~~~~~~~
cuda-sim.cc:137:14: error: invalid use of incomplete type 'const struct textureReference'
  137 |            tr->addressMode[0] == texref->addressMode[0] &&

```

Where textureReference, as far as I can tell, is a feature that was removed from cuda 12.0. 

I went over the Makefile. I have CUDA_INSTALL_PATH set to /usr/local/cuda. 

nvcc --version returns

```
(venv) root@a08aaf42684e:~/Repos/shared/accel-sim-framework/gpu-simulator# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Wed_Jan_15_19:20:09_PST_2025
Cuda compilation tools, release 12.8, V12.8.61
Build cuda_12.8.r12.8/compiler.35404655_0
```

What on earth is wrong with this build? I should also mention that I'm "using" gpgpu v4.2.1 and I checkout accelsim v1.3.0. What is happening? How could the repo claim to support 12.8 so confidently yet fail to build due to a feature deprecated in the version it claims to support? Am I missing something? Please let me know, I'm desperate. 

Thanks!

**Comment by HakamAtassi** [comment]
I hate to say it but the issues just keep getting worse. 

I found an [issue](https://github.com/gpgpu-sim/gpgpu-sim_distribution/issues/315) on the gpgpu sim about the textureReference problem. 

I now gpgpu sim to dev when it asks what version I would like to use. Now building with accelsim v1.3.0 causes

```
                 from main.cc:4:
./trace-driven/../trace-parser/trace_parser.h:38:3: error: 'uint64_t' does not name a type
   38 |   uint64_t addrs[WARP_SIZE];
      |   ^~~~~~~~
./trace-driven/../trace-parser/trace_parser.h:6:1: note: 'uint64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
    5 | #include <stdlib.h>
  +++ |+#include <cstdint>
    6 | #include <string>
./trace-driven/../trace-parser/trace_parser.h:60:3: error: 'uint64_t' does not name a type
   60 |   uint64_t imm;
```



and building with v1.2.0 causes 

```
      |                        ^~~~~~
main.cc: In function 'int main(int, const char**)':
main.cc:121:31: error: no matching function for call to 'gpgpu_sim::print_stats()'
  121 |       m_gpgpu_sim->print_stats();
      |       ~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /root/Repos/shared/accel-sim-framework/gpu-simulator/gpgpu-sim/libcuda/cuda_api_object.h:14,
                 from /root/Repos/shared/accel-sim-framework/gpu-simulator/gpgpu-sim/libcuda/gpgpu_context.h:9:
/root/Repos/shared/accel-sim-framework/gpu-simulator/gpgpu-sim/libcuda/../src/gpgpu-sim/gpu-sim.h:601:8: note: candidate: 'void gpgpu_sim::print_stats(long long unsigned int)'
  601 |   void print_stats(unsigned long long streamID);
      |        ^~~~~~~~~~~

```
literally uses a function that is never declared. I assume this was the result of a bad merge. The current dev causes

```

/root/Repos/shared/accel-sim-framework/gpu-simulator/gpgpu-sim/src/cuda-sim/../gpgpu-sim/gpu-cache.h:1282:3: warning:   when initialized here [-Wreorder]
 1282 |   baseline_cache(const char *name, cache_config &config, int core_id,
      |   ^~~~~~~~~~~~~~
trace_driven.cc: In member function 'virtual const warp_inst_t* trace_shader_core_ctx::get_next_inst(unsigned int, address_type)':
trace_driven.cc:593:30: error: 'class shd_warp_t' has no member named 'test_active'
  593 |         if (m_warp[warp_id]->test_active(t)) {
      |                              ^~~~~~~~~~~
make[1]: Leaving directory '/root/Repos/shared/accel-sim-framework/gpu-simulator/trace-parser'
make[1]: *** [Makefile:58: ../build/release/trace_driven.o] Error 1
make[1]: Leaving directory '/root/Repos/shared/accel-sim-framework/gpu-simulator/trace-driven'
make: *** [Makefile:78: trace-driven] Error 2
make: *** Waiting for unfinished jobs....

```

So it seems like there arent any current checkouts that actually work...

**Comment by HakamAtassi** [comment]
I think v1.3.0 with adding the `#include <cstdint>` header seems to work...

**Comment by William-An** [comment]
You are using `gpgpu-sim/gpgpu-sim_distribution` instead of `accel-sim/gpgpu-sim_distribution`. Our gpgpu-sim repo has this issue fixed in accel-sim/gpgpu-sim_distribution#94

**Comment by HakamAtassi** [comment]
Thanks a lot for the response. I can confirm the issue does seem to be fixed, though there seems to be an environment variable somewhere that was causing my sourcing to pull from the previous GPGPU-sim repo (it wasnt even obvious to me that there was a different fork for accel sim). Its possible the docker is somehow setting that environment variable and breaking the env.

**Comment by JRPan** [comment]
Thanks for the update. Glad to hear the issue was resolved.
It sounds like the problem came from your environment pulling an old GPGPU-Sim path, which isn’t something the project controls. Since everything is working now, I’m going to close this.
